name: PowerShell PR Check

on:
  pull_request:
    paths:
      - "powershell/**"
      - "shared/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  powershell-pr-check:
    name: powershell-pr-check
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/codeql'
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - name: Setup CodeQL
        uses: ./.github/actions/fetch-codeql
        with:
          channel: release
      - name: Compile PowerShell Queries
        run: |
          codeql test run --threads=0 powershell/ql/test
