name: Sync Main

on:
  push:
    branches:
      - main
      - dilan/sync-main-bugs-6
    paths:
      - .github/workflows/sync-main.yml
  schedule:
    - cron: '55 * * * *'
  
jobs:

  sync-main:
  
    name: Sync-main
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/codeql'
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git config
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Add and fetch upstream
        run: |
          echo "::group::Fetch and set up remotes"
          git fetch
          git remote add upstream https://github.com/github/codeql.git
          git fetch upstream --tags --force
          echo "::endgroup::"

          echo "::group::Checkout and merge"
          set -x
          git fetch origin sync-main-pr || true
          git checkout -B sync-main-pr origin/main
          git merge codeql-cli/latest
          set +x
          echo "::endgroup::"
      - name: Push sync branch
        run: |
          git push origin sync-main-pr --force
          # Ensure branch is visible to GitHub
          gh api repos/:owner/:repo/branches/sync-main-pr || {
            echo "Branch not yet visible to GitHub — waiting a bit more"
            sleep 10
          }
          git branch
          gh api repos/:owner/:repo/branches/sync-main-pr || {
            echo "Branch not yet visible to GitHub — waiting a bit more"
            sleep 10
          }
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Create or update PR
        run: |
          git branch
          gh api repos/:owner/:repo/branches/sync-main-pr || {
            echo "Branch not yet visible to GitHub — waiting a bit more"
            sleep 10
          }
          git branch
          gh api repos/:owner/:repo/branches/sync-main-pr
          PR_URL=$(gh pr list --head sync-main-pr --json url --jq '.[0].url')
          if [ -z "$PR_URL" ]; then
            gh pr create \
              --title "Automated sync from upstream" \
              --body "This PR syncs the latest changes from \`codeql-cli/latest\` into \`main\`." \
              --head sync-main-pr \
              --base main
          else
            echo "PR already exists: $PR_URL"
          fi
          exit 0
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

