name: Sync Main

on:
  push:
    branches:
      - main
      - dilan/sync-main-bugs-6
    paths:
      - .github/workflows/sync-main.yml
  schedule:
    - cron: '55 * * * *'
  
jobs:
  sync-main:
    name: Sync-main
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/codeql'
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git config
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B sync-main-pr origin/sync-main-pr
      - name: Sync origin/main
        shell: bash
        run: |
          echo "::group::Sync with main branch"
          git pull origin sync-main-pr; exitCode=$?; if [ $exitCode -ne 0 ]; then exitCode=0; fi
          git pull origin main
          git push --force origin sync-main-pr
          echo "::endgroup::"
      - name: Sync upstream/codeql-cli/latest
        shell: bash
        run: |
          echo "::group::Set up remote"
          git remote add upstream https://github.com/github/codeql.git
          git fetch upstream --tags --force
          echo "::endgroup::"
          echo "::group::Merge codeql-cli/latest"
          set -x
          git merge codeql-cli/latest
          set +x
          echo "::endgroup::"
      - name: Push sync branch
        run: |
          git push origin sync-main-pr
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Create or update PR
        run: |
          if ! gh pr view -R microsoft/codeql -t 'Sync Main' > /dev/null 2>&1; then
            gh pr create --repo microsoft/codeql --fill -B main -H sync-main-pr --title 'Sync Main' --body "This PR syncs the latest changes from \`codeql-cli/latest\` into \`main\`."
          else
            echo "PR 'Sync Main' already exists."
          fi
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

