name: Sync Main

on:
  push:
    branches:
      - main
      - dilan/sync-main-bugs-6
    paths:
      - .github/workflows/sync-main.yml
  schedule:
    - cron: '55 * * * *'
  
jobs:

  sync-main:
    name: Sync-main
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/codeql'
    permissions:
      contents: write
      pull-requests: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git config
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B sync-main-pr origin/sync-main-pr

          echo "::group::Fetch"
          git pull origin sync-main-pr; exitCode=$?; if [ $exitCode -ne 0 ]; then exitCode=0; fi
          # git config pull.rebase true
          git pull origin main
          git push --force origin sync-main-pr
          echo "::endgroup::"

          echo "::group::Set up remote"
          git remote add upstream https://github.com/github/codeql.git
          git fetch upstream --tags --force
          echo "::endgroup::"

          echo "::group::Checkout and merge"
          set -x
          git merge codeql-cli/latest
          set +x
          echo "::endgroup::"
      - name: Push sync branch and ensure visibility
        run: |
          git push origin sync-main-pr
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Debug sync-main-pr state
        run: |
          echo "🔍 Checking sync-main-pr branch and its commit history"
          git status
          
          echo "::group::Diff between sync-main-pr and main"
          git diff main..sync-main-pr
          echo "::endgroup::"
          
          echo "Current SHA for main: $(git rev-parse main)"
          echo "Current SHA for sync-main-pr: $(git rev-parse sync-main-pr)"
      - name: Create or update PR
        run: |
          gh pr create --fill -B main -H sync-main-pr --title 'Sync Main' --body "This PR syncs the latest changes from \`codeql-cli/latest\` into \`main\`."
          exit 0
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}

